name : Waste Service Standards
brand : Waste Service Standards
description : Technical specifications for local waste and recycling services
keyword : 
baseurl : /waste-service-standards
email : 
twitter : 
github : https://github.com/communitiesuk/waste-service-standards
author : Paul Mackay
analytics : 
year : 2016
exclude :
  - lib
  - node_modules
