site_name: Waste Service Standards
site_description: Technical standards for local waste services.
site_favicon: favicon.ico
repo_url: https://github.com/communitiesuk/waste-service-standards

# theme: mkdocs
# theme: readthedocs
theme: bootstrap

extra_css:
- css/custom.css

markdown_extensions:
- markdown_include.include

pages:
- Home: index.md
- Models:
  - Service: models/service.md
  - Event: models/event.md
- Taxonomies:
  - taxonomies/missed-collections.md
- API: api/index.md

